# -----[Color Theme]-----
include nord.conf

# -----[Fonts]-----

# font_family      NotoSansMono
# font_family      FiraMono Nerd Font
# bold_font        FiraMono Nerd Font
# italic_font      FiraMono Nerd Font
# bold_italic_font FiraMono Nerd Font
font_size 14

# -----[Keybinds]-----
map ctrl+backspace send_text all \x17

# -----[Other Settings]-----
# cool cursor animation
# cursor_trail 1
cursor_shape block
enable_audio_bell no
window_padding_width 10
tab_bar_style powerline

# -----[Vim Slime]-----
allow_remote_control yes
listen_on unix:/tmp/mykitty

